CREATE SEQUENCE  "THUEKHOAN"."SEQ_PHONGBAN"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 24 CACHE 20 NOORDER  NOCYCLE ;

create or replace
PROCEDURE PROC_SAVE_PHONGBAN (
  id_	in number,
	name_ in VARCHAR2,
	stt_ IN number,
  deleted_ IN number
) AS 
i INTEGER := 0;
BEGIN
		if(id_ is not null and id_>0) then --update
      update PHONGBAN set TENPHONGBAN = name_ where ID = id_;
	else --insert
		i:=SEQ_PHONGBAN.nextval;
		insert into PHONGBAN(ID,TENPHONGBAN,DELETED,STT) values (i,name_,deleted_,stt_);
  end if;
END PROC_SAVE_PHONGBAN;




--------------------------------------------------------
--  File created - Saturday-September-08-2012   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_MENU
--------------------------------------------------------

  CREATE TABLE "THUEKHOAN"."USER_MENU" 
   (	"ACCOUNTID" NUMBER, 
	"MENUID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "THUEKHOAN"."MENU" 
   (	"ID" NUMBER, 
	"NAMEMENU" VARCHAR2(200 BYTE), 
	"ACTION" VARCHAR2(50 BYTE), 
	"ACTIVE" NUMBER(1,0), 
	"IDROOTMENU" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into THUEKHOAN.USER_MENU
SET DEFINE OFF;
Insert into THUEKHOAN.USER_MENU (ACCOUNTID,MENUID) values (0,1);
Insert into THUEKHOAN.USER_MENU (ACCOUNTID,MENUID) values (0,2);
Insert into THUEKHOAN.USER_MENU (ACCOUNTID,MENUID) values (0,3);
Insert into THUEKHOAN.USER_MENU (ACCOUNTID,MENUID) values (0,4);
Insert into THUEKHOAN.USER_MENU (ACCOUNTID,MENUID) values (0,5);
Insert into THUEKHOAN.USER_MENU (ACCOUNTID,MENUID) values (0,6);
Insert into THUEKHOAN.USER_MENU (ACCOUNTID,MENUID) values (0,7);
Insert into THUEKHOAN.USER_MENU (ACCOUNTID,MENUID) values (0,8);
Insert into THUEKHOAN.USER_MENU (ACCOUNTID,MENUID) values (0,9);
REM INSERTING into THUEKHOAN.MENU
SET DEFINE OFF;
Insert into THUEKHOAN.MENU (ID,NAMEMENU,ACTION,ACTIVE,IDROOTMENU) values (4,'Phòng ban','/danhmuc/phongban.action',1,2);
Insert into THUEKHOAN.MENU (ID,NAMEMENU,ACTION,ACTIVE,IDROOTMENU) values (2,'Quản trị nhóm','/group/index.action',1,1);
Insert into THUEKHOAN.MENU (ID,NAMEMENU,ACTION,ACTIVE,IDROOTMENU) values (3,'Quản trị quy�?n','/menu/index.action',1,1);
Insert into THUEKHOAN.MENU (ID,NAMEMENU,ACTION,ACTIVE,IDROOTMENU) values (1,'Quản trị user','/user/index.action',1,1);
Insert into THUEKHOAN.MENU (ID,NAMEMENU,ACTION,ACTIVE,IDROOTMENU) values (5,'�?ối tác','/danhmuc/doitac.action',1,2);
Insert into THUEKHOAN.MENU (ID,NAMEMENU,ACTION,ACTIVE,IDROOTMENU) values (6,'Dự án','/danhmuc/duan.action',1,2);
Insert into THUEKHOAN.MENU (ID,NAMEMENU,ACTION,ACTIVE,IDROOTMENU) values (7,'Loại dự cố','/danhmuc/phongban.action',1,2);
Insert into THUEKHOAN.MENU (ID,NAMEMENU,ACTION,ACTIVE,IDROOTMENU) values (8,'Tiêu chí bàn giao kênh','/danhmuc/phongban.action',1,2);
Insert into THUEKHOAN.MENU (ID,NAMEMENU,ACTION,ACTIVE,IDROOTMENU) values (9,'Khu vực','/danhmuc/khuvuc.action',1,2);
--------------------------------------------------------
--  DDL for Index USER_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "THUEKHOAN"."USER_MENU_PK" ON "THUEKHOAN"."USER_MENU" ("ACCOUNTID", "MENUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "THUEKHOAN"."MENU_PK" ON "THUEKHOAN"."MENU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_MENU
--------------------------------------------------------

  ALTER TABLE "THUEKHOAN"."USER_MENU" MODIFY ("ACCOUNTID" NOT NULL ENABLE);
 
  ALTER TABLE "THUEKHOAN"."USER_MENU" MODIFY ("MENUID" NOT NULL ENABLE);
 
  ALTER TABLE "THUEKHOAN"."USER_MENU" ADD CONSTRAINT "USER_MENU_PK" PRIMARY KEY ("ACCOUNTID", "MENUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "THUEKHOAN"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "THUEKHOAN"."MENU" MODIFY ("ID" NOT NULL ENABLE);





