ALTER TABLE DOISOATCUOC 
ADD (TONGDAUNOIHOAMANG NUMBER );

ALTER TABLE DOISOATCUOC 
ADD (TONGDATHANHTOAN NUMBER );

ALTER TABLE DOISOATCUOC 
ADD (TONGCONTHANHTOAN NUMBER );

ALTER TABLE PHONGBAN  
MODIFY (DELETED NUMBER );

ALTER TABLE DOITAC  
MODIFY (DELETED NUMBER );

ALTER TABLE DUAN  
MODIFY (DELETED NUMBER );

ALTER TABLE CONGTHUC  
MODIFY (DELETED NUMBER );

ALTER TABLE TIEUCHUAN  
MODIFY (DELETED NUMBER );

ALTER TABLE KHUVUC  
MODIFY (DELETED NUMBER );

ALTER TABLE LOAIGIAOTIEP  
MODIFY (DELETED NUMBER );