drop table "THUEKENH"."TUYENKENH_BANGIAO" cascade constraints ;

ALTER TABLE TUYENKENH 
DROP COLUMN SOLUONG;

ALTER TABLE TUYENKENH 
DROP COLUMN NGAYDENGHIBANGIAO;

ALTER TABLE TUYENKENH 
DROP COLUMN NGAYHENBANGIAO;

ALTER TABLE TUYENKENH 
DROP COLUMN THONGTINLIENHE;

ALTER TABLE TUYENKENH_TIEUCHUAN RENAME COLUMN TUYENKENH_ID TO TUYENKENHDEXUAT_ID;

CREATE TABLE TUYENKENHDEXUAT 
(
  ID NUMBER NOT NULL 
, DEXUAT_ID NUMBER 
, TUYENKENH_ID NUMBER 
, BANGIAO_ID NUMBER 
, NGAYDENGHIBANGIAO DATE 
, NGAYHENBANGIAO DATE 
, THONGTINLIENHE VARCHAR2(1000) 
, TRANGTHAI NUMBER(2, 0) 
, CONSTRAINT TUYENKENHDEXUAT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


ALTER TABLE DEXUAT 
RENAME TO VANBANDEXUAT;

ALTER TABLE VANBANDEXUAT 
ADD (DEXUAT_ID NUMBER );


drop table "THUEKENH"."DEXUAT_TUYENKENH" cascade constraints ;

CREATE TABLE DEXUAT 
(
  ID NUMBER 
, TENDEXUAT VARCHAR2(200) 
, USERCREATE VARCHAR2(200) 
, TIMECREATE DATE 
, DELETED NUMBER 
);

ALTER TABLE DEXUAT  
MODIFY (ID NOT NULL);

ALTER TABLE DEXUAT
ADD CONSTRAINT DEXUAT_PK1 PRIMARY KEY 
(
  ID 
)
ENABLE;

