ALTER TABLE TUYENKENH_HISTORY 
RENAME TO LICHSU_TUYENKENH;

ALTER TABLE LICHSU_TUYENKENH 
DROP COLUMN ACTION;

ALTER TABLE LICHSU_TUYENKENH  
MODIFY (TIMEACTION NUMBER );

ALTER TABLE LICHSU_TUYENKENH 
DROP CONSTRAINT TUYENKENH_HISTORY_PK;

ALTER TABLE LICHSU_TUYENKENH 
DROP COLUMN ID;

ALTER TABLE LICHSU_TUYENKENH  
MODIFY (TIMEACTION DATE );

ALTER TABLE LICHSU_TUYENKENH 
ADD (ACTION NUMBER );


