ALTER TABLE TUYENKENH 
ADD (SOLUONG NUMBER );

ALTER TABLE TUYENKENH  
MODIFY (ID DEFAULT 0 );

ALTER TABLE TUYENKENHDEXUAT 
ADD (SOLUONG NUMBER DEFAULT 0 );

drop table "THUEKENH"."DEXUAT" cascade constraints ;

ALTER TABLE VANBANDEXUAT 
RENAME TO DEXUAT;

CREATE SEQUENCE SEQ_TUYENKENHDEXUAT INCREMENT BY 1 START WITH 1 MAXVALUE 999999 MINVALUE 1;

ALTER TABLE TUYENKENHDEXUAT 
ADD (DELETED NUMBER DEFAULT 0 );

ALTER TABLE TUYENKENH 
ADD (TRANGTHAI_BAK NUMBER DEFAULT 0 );

