ALTER TABLE PHULUC 
DROP COLUMN FILESCAN_ID;

ALTER TABLE PHULUC 
ADD (FILENAME VARCHAR2(200) );

ALTER TABLE PHULUC 
ADD (FILEPATH VARCHAR2(200) );

ALTER TABLE PHULUC 
ADD (FILESIZE VARCHAR2(20) );

ALTER TABLE THANHTOAN 
DROP COLUMN FILESCAN_ID;

ALTER TABLE THANHTOAN 
ADD (FILENAME VARCHAR2(200) );

ALTER TABLE THANHTOAN 
ADD (FILEPATH VARCHAR2(200) );

ALTER TABLE THANHTOAN 
ADD (FILESIZE VARCHAR2(20) );

ALTER TABLE PHULUC 
ADD (PHULUCTHAYTHE_ID NUMBER );
