DECLARE
  ID_ VARCHAR2(200);
  TUYENKENH_ID_ VARCHAR2(200);
  FILESCAN_ID_ VARCHAR2(200);
  PHULUC_ID_ VARCHAR2(200);
  THANHTOAN_ID_ VARCHAR2(200);
  LOAISUCO_ VARCHAR2(200);
  THOIDIEMBATDAU_ VARCHAR2(200);
  THOIDIEMKETTHUC_ VARCHAR2(200);
  THOIGIANMLL_ VARCHAR2(200);
  NGUYENNHAN_ VARCHAR2(200);
  PHUONGANXULY_ VARCHAR2(200);
  NGUOIXACNHAN_ VARCHAR2(200);
  GIAMTRUMLL_ VARCHAR2(200);
  TRANGTHAI_ VARCHAR2(200);
  USERCREATE_ VARCHAR2(200);
  TIMECREATE_ VARCHAR2(200);
  DELETED_ VARCHAR2(200);
  v_Return NUMBER;
BEGIN
  ID_ := NULL;
  TUYENKENH_ID_ := NULL;
  FILESCAN_ID_ := NULL;
  PHULUC_ID_ := NULL;
  THANHTOAN_ID_ := NULL;
  LOAISUCO_ := NULL;
  THOIDIEMBATDAU_ := NULL;
  THOIDIEMKETTHUC_ := NULL;
  THOIGIANMLL_ := NULL;
  NGUYENNHAN_ := NULL;
  PHUONGANXULY_ := NULL;
  NGUOIXACNHAN_ := NULL;
  GIAMTRUMLL_ := NULL;
  TRANGTHAI_ := NULL;
  USERCREATE_ := NULL;
  TIMECREATE_ := NULL;
  DELETED_ := NULL;

  v_Return := SAVE_SUCOKENH(
    ID_ => ID_,
    TUYENKENH_ID_ => TUYENKENH_ID_,
    FILESCAN_ID_ => FILESCAN_ID_,
    PHULUC_ID_ => PHULUC_ID_,
    THANHTOAN_ID_ => THANHTOAN_ID_,
    LOAISUCO_ => LOAISUCO_,
    THOIDIEMBATDAU_ => THOIDIEMBATDAU_,
    THOIDIEMKETTHUC_ => THOIDIEMKETTHUC_,
    THOIGIANMLL_ => THOIGIANMLL_,
    NGUYENNHAN_ => NGUYENNHAN_,
    PHUONGANXULY_ => PHUONGANXULY_,
    NGUOIXACNHAN_ => NGUOIXACNHAN_,
    GIAMTRUMLL_ => GIAMTRUMLL_,
    TRANGTHAI_ => TRANGTHAI_,
    USERCREATE_ => USERCREATE_,
    TIMECREATE_ => TIMECREATE_,
    DELETED_ => DELETED_
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('v_Return = ' || v_Return);
*/ 
  :v_Return := v_Return;
END;
