ALTER TABLE THANHTOAN 
ADD (NGAYKYUNC DATE );

ALTER TABLE THANHTOAN 
ADD (NGAYCHUYENKHOAN DATE );

ALTER TABLE THANHTOAN 
ADD (TIMEUPDATE DATE );

ALTER TABLE THANHTOAN
ADD CONSTRAINT THANHTOAN_UK1 UNIQUE 
(
  SOHOSO 
, DELETED 
)
ENABLE;
